### ISSUE TITLE
Dosen't highlight the best tip mould for the commsion

### ISSUE THREAD

**Issue by Hansen13** [Lawst96/giants-foundry-mould-helper#1]
![image](https://user-images.githubusercontent.com/90900054/173788017-0dd455fa-27cc-4312-abef-14323782b886.png)

**Comment by Lawst96** [comment]
Are you sure you are using my plugin? It's currently not available through the plugin hub. A similar plugin called [Easy Giants' Foundry](https://github.com/Toofifty/easy-giantsfoundry) is.
